# Generated by Django 5.0.6 on 2024-05-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Especie',
            new_name='Filo',
        ),
    ]
