# Generated by Django 5.0.6 on 2024-05-28 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0002_rename_especie_filo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('filo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais.filo')),
            ],
        ),
    ]
