# Generated by Django 5.0.6 on 2024-05-28 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0003_especie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Especie',
            new_name='Subfilo',
        ),
        migrations.AlterField(
            model_name='filo',
            name='reino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filos', to='animais.reino'),
        ),
    ]
