# Generated by Django 5.0.6 on 2024-05-28 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0004_rename_especie_subfilo_alter_filo_reino'),
    ]

    operations = [
        migrations.AddField(
            model_name='reino',
            name='imagem',
            field=models.ImageField(default='default.webp', upload_to='images/reinos/animalia.webp'),
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('subfilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='animais.subfilo')),
            ],
        ),
    ]
