# Generated by Django 5.0.6 on 2024-05-28 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0005_reino_imagem_especie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reino',
            name='imagem',
            field=models.ImageField(default='animalia.webp', upload_to='animais/images/reinos/'),
        ),
    ]
