# Generated by Django 5.0.6 on 2024-05-28 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0010_alter_reino_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reino',
            name='imagem',
            field=models.ImageField(upload_to='media/reinos/default'),
        ),
    ]
