# Generated by Django 5.0.6 on 2024-05-29 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0013_alter_reino_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='especie',
            name='subfilo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='especies', to='animais.subfilo'),
        ),
        migrations.AlterField(
            model_name='filo',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='reino',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='subfilo',
            name='filo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subfilos', to='animais.filo'),
        ),
        migrations.AlterField(
            model_name='subfilo',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
