# Generated by Django 5.0.6 on 2024-06-05 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0014_alter_especie_nome_alter_especie_subfilo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='especie',
            name='subfilo',
        ),
        migrations.AlterField(
            model_name='especie',
            name='nome',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('filo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='animais.filo')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, unique=True)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generos', to='animais.familia')),
            ],
        ),
        migrations.AddField(
            model_name='especie',
            name='genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='especies', to='animais.genero'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Ordem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens', to='animais.classe')),
            ],
        ),
        migrations.AddField(
            model_name='familia',
            name='ordem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='familias', to='animais.ordem'),
        ),
        migrations.DeleteModel(
            name='Subfilo',
        ),
    ]
