# Generated by Django 5.0.6 on 2024-06-05 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0015_familia_remove_especie_subfilo_alter_especie_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
