# Generated by Django 5.0.6 on 2024-06-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0016_alter_especie_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='especie',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='familia',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='filo',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='genero',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AddField(
            model_name='ordem',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='reino',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
