# Generated by Django 5.0.6 on 2024-06-11 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0017_classe_imagem_especie_imagem_familia_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='descricao',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='especie',
            name='descricao',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='familia',
            name='descricao',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='filo',
            name='descricao',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='genero',
            name='descricao',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ordem',
            name='descricao',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='reino',
            name='descricao',
            field=models.CharField(default='', max_length=255),
        ),
    ]
