# Generated by Django 5.0.6 on 2024-06-11 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0018_classe_descricao_especie_descricao_familia_descricao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='descricao',
            field=models.CharField(default='', max_length=2555),
        ),
        migrations.AlterField(
            model_name='especie',
            name='descricao',
            field=models.CharField(default='', max_length=2555),
        ),
        migrations.AlterField(
            model_name='familia',
            name='descricao',
            field=models.CharField(default='', max_length=2555),
        ),
        migrations.AlterField(
            model_name='filo',
            name='descricao',
            field=models.CharField(default='', max_length=2555),
        ),
        migrations.AlterField(
            model_name='genero',
            name='descricao',
            field=models.CharField(default='', max_length=2555),
        ),
        migrations.AlterField(
            model_name='ordem',
            name='descricao',
            field=models.CharField(default='', max_length=2555),
        ),
        migrations.AlterField(
            model_name='reino',
            name='descricao',
            field=models.CharField(default='', max_length=2555),
        ),
    ]
