# Generated by Django 5.0.6 on 2024-06-11 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0019_alter_classe_descricao_alter_especie_descricao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='especie',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='familia',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='filo',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='genero',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='ordem',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='reino',
            name='descricao',
        ),
    ]
